package de.modulo.backend.dtos;

import lombok.Data;

@Data
public class DegreeDTO {

    private Long id;
    private String name;

    // No arguments constructor and other methods are generated by Lombok
}
