package de.modulo.backend.dtos;

import lombok.Data;

@Data
public class ModuleTypeDTO {

    private long id;
    private int index;
    private Long spoId; // To reference the SpoEntity ID
    private String name;

    // No arguments constructor and other methods are automatically generated by Lombok
}
