package de.modulo.backend.dtos;

import lombok.Data;

@Data
public class SectionDTO {

    private Long id;
    private int index;
    private String name;
    private Long spoId;

    // No arguments constructor and other methods are generated by Lombok
}
